#:schema node_modules/wrangler/config-schema.json
name = "api-nodejs-hello-world"
pages_build_output_dir = ".worker-next/assets"
compatibility_date = "2024-07-01"
compatibility_flags = ["experimental:nodejs_compat_v2"]

# # The aliases below should not be needed (we don't want users to have to define the aliases themselves)
# [alias]
# # critters is `require`d from `pages.runtime.prod.js` when running wrangler dev, so we need to stub it out
# "critters" = "../../nextjs-worker-builder/src/build/build-worker/templates/shims/empty.ts"
# # @opentelemetry/api is `require`d when running wrangler dev, so we need to stub it out
# "@opentelemetry/api" = "../../nextjs-worker-builder/src/build/build-worker/templates/shims/empty.ts"
